[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JCGEImportMPSGE = "f07e4517-cb44-4ce3-be1e-24c689785741"

[sources]
JCGEImportMPSGE = { path = ".." }
JCGECore = { url = "https://github.com/equicirco/JCGECore.jl" }
JCGECalibrate = { url = "https://github.com/equicirco/JCGECalibrate.jl" }
JCGEBlocks = { url = "https://github.com/equicirco/JCGEBlocks.jl" }
